### PR TITLE
Update ItemAPI for LLSE

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by futrime — APPROVED** [review]
Good job, your pr will be merged into the repository once the corresponding pr to the main repo is merged.

**Comment by Jaciezyt** [comment]
LiteLDev/LiteLoaderBDS#769 has merged

**Comment by Jaciezyt** [comment]
Wait, Chinese documentation needs translation

**Comment by futrime** [comment]
@Jasonzyt It's OK to approve the PR, for the translation can be done by others.

**Comment by ghost** [comment]
> Wait, Chinese documentation needs translation

I don't know Chinese, so I just I leave lines for translation. [Check this](https://github.com/LiteLDev/docs/pull/4#issuecomment-1239069662)

**Pull request merged**
